-- SOLVANTO XEVORA WEBSITE SETUP
-- Run this entire script in Supabase SQL Editor.
-- Upload the installer to a PRIVATE Storage bucket named software.

create table if not exists public.profiles (
 id uuid primary key references auth.users(id) on delete cascade,
 username text not null unique,
 created_at timestamptz not null default now(),
 constraint username_format check (username ~ '^[A-Za-z0-9_]{3,30}$')
);
create table if not exists public.private_feedback (
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 subject text not null check (char_length(subject) between 1 and 120),
 message text not null check (char_length(message) between 1 and 4000),
 created_at timestamptz not null default now()
);
create table if not exists public.site_visits (
 id bigint generated by default as identity primary key,
 visitor_id text not null,
 page text not null default 'home',
 created_at timestamptz not null default now()
);
create table if not exists public.software_downloads (
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 software text not null,
 version text not null,
 created_at timestamptz not null default now()
);
create table if not exists public.site_config (
 id integer primary key check(id=1),
 config jsonb not null,
 updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.private_feedback enable row level security;
alter table public.site_visits enable row level security;
alter table public.software_downloads enable row level security;
alter table public.site_config enable row level security;

-- Profiles
 drop policy if exists "profiles own read" on public.profiles;
 create policy "profiles own read" on public.profiles for select to authenticated using (id=auth.uid());
 drop policy if exists "profiles own insert" on public.profiles;
 create policy "profiles own insert" on public.profiles for insert to authenticated with check (id=auth.uid());

-- Private support messages
 drop policy if exists "feedback own insert" on public.private_feedback;
 create policy "feedback own insert" on public.private_feedback for insert to authenticated with check (user_id=auth.uid());
 drop policy if exists "feedback own read" on public.private_feedback;
 create policy "feedback own read" on public.private_feedback for select to authenticated using (user_id=auth.uid());

-- Visit tracking
 drop policy if exists "anonymous visit tracking" on public.site_visits;
 create policy "anonymous visit tracking" on public.site_visits for insert to anon,authenticated with check (char_length(visitor_id) between 10 and 100);

-- Download event tracking
 drop policy if exists "own download log insert" on public.software_downloads;
 create policy "own download log insert" on public.software_downloads for insert to authenticated with check (user_id=auth.uid());

-- Public website configuration can be read by everyone; only the owner can change it.
 drop policy if exists "public can read site config" on public.site_config;
 create policy "public can read site config" on public.site_config for select to anon,authenticated using (true);
 drop policy if exists "owner can insert site config" on public.site_config;
 create policy "owner can insert site config" on public.site_config for insert to authenticated with check(lower(coalesce(auth.jwt()->>'email',''))='solvantoxevora@gmail.com');
 drop policy if exists "owner can update site config" on public.site_config;
 create policy "owner can update site config" on public.site_config for update to authenticated using(lower(coalesce(auth.jwt()->>'email',''))='solvantoxevora@gmail.com') with check(lower(coalesce(auth.jwt()->>'email',''))='solvantoxevora@gmail.com');

insert into storage.buckets(id,name,public) values('software','software',false) on conflict(id) do update set public=false;
drop policy if exists "authenticated can read software" on storage.objects;
create policy "authenticated can read software" on storage.objects for select to authenticated using(bucket_id='software');

create or replace function public.get_site_stats()
returns json language plpgsql security definer set search_path=public as $$
declare caller_email text:=lower(coalesce(auth.jwt()->>'email',''));
begin
 if caller_email<>'solvantoxevora@gmail.com' then raise exception 'not authorized'; end if;
 return json_build_object(
  'registered_users',(select count(*) from public.profiles),
  'download_events',(select count(*) from public.software_downloads),
  'unique_downloaders',(select count(distinct user_id) from public.software_downloads),
  'unique_visitors',(select count(distinct visitor_id) from public.site_visits)
 );
end;$$;
revoke all on function public.get_site_stats() from public;
grant execute on function public.get_site_stats() to authenticated;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
begin
 insert into public.profiles(id,username) values(new.id,coalesce(new.raw_user_meta_data->>'username','user_'||substr(new.id::text,1,8)));
 return new;
end;$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

-- Initial editable configuration. This is used only if the row does not already exist.
insert into public.site_config(id,config) values(1,'{}'::jsonb) on conflict(id) do nothing;
